# -*- coding: utf-8 -*-
"""atividade_avaliativa_10_joana_morais_est

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZaMRRr0sz9i9Nzvbonxnag2o5buOHQgT

### **(A) Escolha adequadamente X e Y:**

Tomamos consumo de cigarros como variável independente X e os números de mortes como variável dependente de X. Investiga-se a relação de dependência entre o fato do número de morte aumentar devido ao consumo de cigarro.

### **(B) Construa o diagrama de dispersão entre X e Y.**
"""

import matplotlib.pyplot as plt

#Sejam os dados a seguir, aqueles disponibilizados pela questão 106.
consumo_de_cigarros = [240, 255, 340, 375, 510, 490, 490, 180, 1125, 1150, 1275]
mortes_por_habitantes = [63, 100, 140, 175, 160, 180, 250, 180, 360, 470, 200]

plt.scatter(consumo_de_cigarros, mortes_por_habitantes)

plt.title('Diagrama de Dispersão Linear')
plt.xlabel('Consumo de cigarros')
plt.ylabel('Mortes (por 10⁶ hab)')

plt.show()
print()

"""### (C)
Vamos agora utilizar do python para sabermos o tamanho da nossa mostra, bem como a somatória dos valores dos dados apresentados. 
"""

consumo_de_cigarros_ao_quadrado = [x**2 for x in consumo_de_cigarros]
print(consumo_de_cigarros_ao_quadrado)

n = len(consumo_de_cigarros)
print(n)

print('somatorio de todos os valores contidos no vetor consumo de cigarros:')
soma_valores_consumo_cigarro = sum(consumo_de_cigarros)
print(soma_valores_consumo_cigarro)

print('somatorio de todos os valores contidos no vetor consumo de cigarros AO QUADRADO:')
soma_valores_consumo_cigarro_quadrado = soma_valores_consumo_cigarro ** 2
print(soma_valores_consumo_cigarro_quadrado)

consumo_de_cigarros_ao_quadrado = [x**2 for x in consumo_de_cigarros]
print(consumo_de_cigarros_ao_quadrado)

somatorio = sum(consumo_de_cigarros_ao_quadrado)
print(somatorio)

sxx = 11*(somatorio) - soma_valores_consumo_cigarro_quadrado
print(sxx)


#print(somatorio_dados_consumo_cigarro)
#quadrado_do_somatorio_consumo = somatorio_dados_consumo_cigarro ** 2
#print(quadrado_do_somatorio_consumo)

mortes_por_habitantes


mortes_por_habitantes_ao_quadrado = [x**2 for x in mortes_por_habitantes]
print(mortes_por_habitantes_ao_quadrado)

somatorio = sum(mortes_por_habitantes_ao_quadrado)
print("somatório das mortes ao quadrado: ", somatorio)

sum_y = sum(mortes_por_habitantes)
quadratic_sum_y = sum_y **2
print("somatório ao quadrado das mortes: ", quadratic_sum_y)

print(607594 *11)

print(6683534 - 5189284)

vetor_resultado = [x * y for x, y in zip(consumo_de_cigarros, mortes_por_habitantes)]
print("Vetor resultante da multiplicação de ambos os vetores: ", vetor_resultado)
print()
somatorio_vetor_resultante = sum(vetor_resultado)
print("Σxy: ", somatorio_vetor_resultante)

print()
sum_x = sum(consumo_de_cigarros)
print("Σx: ", sum_x)
print()
sum_y = sum(mortes_por_habitantes)
print("Σy: ", sum_y)

Sxy = (n * somatorio_vetor_resultante) - (sum_x * sum_y)
print("Sxy: ", Sxy)

Sxx = 17673400
Syy = 1494250

# Calculo da correlação amostral
from math import sqrt

coef_de_correlacao = ((Sxy) / sqrt(Sxx * Syy))
print("correlação: ", coef_de_correlacao)

beta_1 = Sxy / Sxx
print("Valor do beta_1: ", beta_1)

beta_zero = (sum_y / n) - (beta_1 * (sum_x / n))
print("Valor do beta_zero: ", beta_zero)

"""## Fórmula da equação de regressão:
(I) y = beta_zero + beta_1 * x
<br><br>
Substituindo-se os valores de beta_zero e beta_1 na fórmula (I), temos, finalmente:  <br><br>
**y = 80.68 + 0.21*x**
<br>
<br>
*Interpretação*: o valor do coeficiente angular beta_1 indica a inclinação da reta, enquanto o beta zero é o termo independente. Entende-se pelo beta zero, também, pelo número de mortes quando não há consumo de cigarro.

##(E) Se, no ano de 1930, o consumo de cigarros per capta no Brasil foi 630, estime o número de mortes causadas por câncer de pulmão no ano de 1950.
"""

# substituindo x no modelo de regressão linear proposto em (I):
x = 630
y = beta_zero + beta_1 * 630
print(y)

print("Para o consumo de cigarros per capta igual a 630, o número de mortes de câncer de pulmão no Brasil foi de aproximadamente: ", round(y))

"""##**(F) Calcule e interprete o coeficiente de determinação R2 para a equação de regressão estimada no item (d).**"""

R_ao_quadrado = coef_de_correlacao ** 2
print("R² = corr(x,y)² = ", R_ao_quadrado)

"""Ou seja, 55,31% da variação do número de mortes causadas por câncer de pulmão podem ser explicadas pelo consumo de cigarro."""